### ISSUE TITLE
Compiled release?

### ISSUE THREAD

**Issue by Keith94** [ZUKMAN/WC3WIDESCREENFIX#1]
Hi, this seems like a useful widescreen solution for this game. Can you provide a ready-to-download release for it, if it's still working correctly?

**Comment by ZUKMAN** [comment]
It's old and not working properly. Use Renderedge instead. [http://www.hiveworkshop.com/threads/renderedge-basic-version.288375/](url)

**Comment by Keith94** [comment]
Cool, thanks for telling me.
